[project]
name = "production-ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "blockchainarchitect9", email = "blockchainarchitect9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "altair>=6.2.2",
    "click>=8.4.2",
    "datasets>=5.0.1",
    "gputil>=1.4.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "spacy>=3.8.13",
    "torch>=2.13.0",
]

[project.scripts]
production-ai-engineering = "production_ai_engineering:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
